import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0d0e13',
        'surface-container-low': '#121319',
        'surface-container': '#181920',
        'surface-container-high': '#1e1f26',
        'surface-container-highest': '#24252d',
        'surface-bright': '#2a2c34',
        'surface-variant': '#24252d',
        'surface-dim': '#0d0e13',
        'surface-tint': '#81ecff',
        'surface-container-lowest': '#000000',
        background: '#0d0e13',
        on_background: '#f7f5fd',
        on_surface: '#f7f5fd',
        'on-surface-variant': '#abaab1',
        'inverse-surface': '#faf8ff',
        'inverse-on-surface': '#54545b',
        'inverse-primary': '#006976',
        outline: '#75757b',
        'outline-variant': '#47474e',
        primary: '#81ecff',
        'primary-dim': '#00d4ec',
        'primary-fixed': '#00e3fd',
        'primary-fixed-dim': '#00d4ec',
        'on-primary': '#005762',
        'on-primary-fixed': '#003840',
        'on-primary-fixed-variant': '#005762',
        'on-primary-container': '#004d57',
        'primary-container': '#00e3fd',
        secondary: '#a68cff',
        'secondary-dim': '#7e51ff',
        'secondary-fixed': '#d8caff',
        'secondary-fixed-dim': '#cabaff',
        'on-secondary': '#25006b',
        'on-secondary-fixed': '#3b00a0',
        'on-secondary-fixed-variant': '#591bdc',
        'on-secondary-container': '#e4daff',
        'secondary-container': '#591adc',
        tertiary: '#6e9bff',
        'tertiary-dim': '#0f6df3',
        'tertiary-fixed': '#8eafff',
        'tertiary-fixed-dim': '#77a1ff',
        'on-tertiary': '#001d4e',
        'on-tertiary-fixed': '#00163d',
        'on-tertiary-fixed-variant': '#003580',
        'on-tertiary-container': '#000000',
        'tertiary-container': '#2778fe',
        error: '#ff716c',
        'error-dim': '#d7383b',
        'on-error': '#490006',
        'on-error-container': '#ffa8a3',
        'error-container': '#9f0519',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        'neon-cyan': '0 0 15px rgba(129, 236, 255, 0.4)',
        'neon-violet': '0 0 15px rgba(166, 138, 255, 0.4)',
        'neon-sky': '0 0 15px rgba(110, 155, 255, 0.4)',
        'glass': '0 0 20px rgba(129, 236, 255, 0.15)',
        'deep': '0 40px 40px rgba(0, 0, 0, 0.5)',
      },
      backdropBlur: {
        'glass': '24px',
      },
    },
  },
  plugins: [],
}
export default config
